-- INSERT
CREATE TRIGGER TR_AUDITORIA_USUARIOS_INSERT
ON Usuarios
AFTER INSERT
AS
BEGIN
  INSERT INTO Auditoria
  SELECT NEWID(), 'Usuarios', 'INSERT', GETDATE(), SYSTEM_USER, (SELECT * FROM inserted FOR JSON AUTO)
END;

-- UPDATE
CREATE TRIGGER TR_AUDITORIA_USUARIOS_UPDATE
ON Usuarios
AFTER UPDATE
AS
BEGIN
  INSERT INTO Auditoria
  SELECT NEWID(), 'Usuarios', 'UPDATE', GETDATE(), SYSTEM_USER, (SELECT * FROM inserted FOR JSON AUTO)
END;

-- DELETE
CREATE TRIGGER TR_AUDITORIA_USUARIOS_DELETE
ON Usuarios
AFTER DELETE
AS
BEGIN
  INSERT INTO Auditoria
  SELECT NEWID(), 'Usuarios', 'DELETE', GETDATE(), SYSTEM_USER, (SELECT * FROM deleted FOR JSON AUTO)
END;
